language: objective-c

osx_image: xcode7.3

sudo: false # Enable container-based builds

before_install:
  - brew update
  - brew outdated xctool || brew upgrade xctool
script: script/cibuild

branches:
  only: # whitelist
    - master

notifications:
  email: false
